apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
      annotations:
    spec:
      volumes:
        - name: mosquitto
          persistentVolumeClaim:
            claimName: mosquitto
        - name: mosquitto-config
          configMap:
            name: mosquitto
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: mosquitto
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config
          env:
            - name: TZ
              value: America/Detroit
          resources:
            requests:
              memory: '128Mi'
            limits:
              memory: '128Mi'
