#!/usr/bin/env bash
set -e
set -x

cd $MISE_PROJECT_ROOT/talos

#MISE description="Apply talhelper config"
#MISE depends=["talos:setup"]
#USAGE flag "--reboot" help="apply with reboot"

command="apply"
reboot=""
insecure=""

if [ "$usage_reboot" == "true" ]; then
    reboot="--extra-flags='--mode=reboot'"
fi

if ! talosctl health --wait-timeout=5s >/dev/null 2>&1; then
    insecure="--extra-flags='--insecure'"
fi

generated=$(talhelper gencommand $command $insecure $reboot)
echo $generated
eval $generated
