apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: pete@petekeen.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyIDSecretRef:
            name: cert-manager-credentials
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: cert-manager-credentials
            key: AWS_SECRET_ACCESS_KEY
