---
clusterName: nimbus
talosVersion: 1.10.6
kubernetesVersion: 1.33.4
endpoint: https://10.73.95.73:6443
domain: nimbus.keen.land
allowSchedulingOnControlPlanes: true
patches:
  - |-
    machine:
      network:
        kubespan:
          enabled: true
          advertiseKubernetesNetworks: true
      kubelet:
        extraArgs:
          rotate-server-certificates: true
      features:
        hostDNS:
          resolveMemberNames: true

  - |-
    cluster:
      network:
        podSubnets:
          - 10.245.0.0/16
        serviceSubnets:
          - 10.97.0.0/12
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service: {}

controlPlane:
  patches:
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:reader
              - os:etcd:backup
            allowedKubernetesNamespaces:
              - kube-system
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
          - siderolabs/i915
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

nodes:
  - hostname: nimbus
    ipAddress: 10.73.95.73
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        addresses:
          - 10.73.95.73/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.73.95.1
            metric: 1024
    userVolumes:
      - name: local-path-provisioner-3
        provisioning:
          diskSelector:
            match: disk.transport == "virtio"
          minSize: 10GiB
          grow: true
