kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant-configs-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
