---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/b6ql6t6e7bp4tywelpyw7vvcfu"
